/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mesen_demo_MesenAPI */

#ifndef _Included_com_example_mesen_demo_MesenAPI
#define _Included_com_example_mesen_demo_MesenAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mesen_demo_MesenAPI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mesen_demo_MesenAPI_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_mesen_demo_MesenAPI
 * Method:    initializeEmu
 * Signature: (Ljava/lang/String;ZZZ)V
 */
JNIEXPORT void JNICALL Java_com_example_mesen_demo_MesenAPI_initializeEmu
  (JNIEnv *, jclass, jstring, jboolean, jboolean, jboolean);

/*
 * Class:     com_example_mesen_demo_MesenAPI
 * Method:    registerNotificationCallback
 * Signature: (Lcom/example/mesen/demo/MesenAPI/NotificationCallback;)V
 */
JNIEXPORT void JNICALL Java_com_example_mesen_demo_MesenAPI_registerNotificationCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_mesen_demo_MesenAPI
 * Method:    loadROM
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mesen_demo_MesenAPI_loadROM
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_mesen_demo_MesenAPI
 * Method:    setKeyState
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_example_mesen_demo_MesenAPI_setKeyState
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
