name: Build Mesen C API

on: 
  workflow_dispatch

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Install
        run: |
          cmake --install build --prefix dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MesenRT
          path: dist

