name: Build Mesen C API

on: 
  workflow_dispatch

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup CMake
        uses: Symbitic/install-cmake@v0.1.0
      - name: configure
        run: |
          cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: |
          cmake --build build -j
        
